import Head from "next/head";
import React from "react";
import PrimarySearchAppBar from "./Header";

const Layout = ({ children, paginas }) => {
  return (
    <>
      <Head>
        <title>Todo List - {paginas}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/My_Logo.jpg" />
      </Head>
      <PrimarySearchAppBar />
      {children}
      {/* <Footer/> */}
    </>
  );
};

export default Layout;